import { fileURLToPath } from 'node:url'
import { expect, it } from 'vitest'
import { listPackageDependencies } from '../src'

it('get package list', async () => {
  const list = await listPackageDependencies({
    cwd: fileURLToPath(new URL('..', import.meta.url)),
    depth: 25,
    monorepo: false,
  })

  const item = Array.from(list.packages.values()).find(i => i.name === 'debug')

  expect(item).toMatchInlineSnapshot(`
    {
      "dependencies": Set {
        "ms@2.1.3",
      },
      "dependents": Set {
        "@babel/core@7.26.7",
        "@babel/traverse@7.26.7",
        "ms@2.1.3",
        "@babel/parser@7.26.7",
        "@ampproject/remapping@2.3.0",
        "@jridgewell/trace-mapping@0.3.25",
        "@jridgewell/resolve-uri@3.1.2",
        "@jridgewell/gen-mapping@0.3.8",
        "@jridgewell/set-array@1.2.1",
        "@babel/generator@7.26.5",
        "jsesc@3.1.0",
        "@babel/helper-compilation-targets@7.26.5",
        "@babel/compat-data@7.26.5",
        "@babel/helper-validator-option@7.25.9",
        "lru-cache@5.1.1",
        "yallist@3.1.1",
        "browserslist@4.24.4",
        "caniuse-lite@1.0.30001697",
        "electron-to-chromium@1.5.93",
        "node-releases@2.0.19",
        "update-browserslist-db@1.1.2",
        "escalade@3.2.0",
        "@babel/template@7.25.9",
        "@babel/helpers@7.26.7",
        "globals@11.12.0",
        "@babel/helper-module-transforms@7.26.0",
        "@babel/helper-module-imports@7.25.9",
        "mkdist@2.2.0",
        "jiti@1.21.7",
        "pathe@1.1.2",
        "postcss@8.5.1",
        "nanoid@3.3.8",
        "source-map-js@1.2.1",
        "postcss-nested@7.0.2",
        "postcss-selector-parser@7.0.0",
        "cssesc@3.0.0",
        "autoprefixer@10.4.20",
        "fraction.js@4.3.7",
        "normalize-range@0.1.2",
        "postcss-value-parser@4.2.0",
        "cssnano@7.0.6",
        "lilconfig@3.1.3",
        "cssnano-preset-default@7.0.6",
        "css-declaration-sorter@7.2.0",
        "cssnano-utils@5.0.0",
        "postcss-calc@10.1.1",
        "postcss-discard-comments@7.0.3",
        "postcss-selector-parser@6.1.2",
        "postcss-discard-duplicates@7.0.1",
        "postcss-discard-empty@7.0.0",
        "postcss-discard-overridden@7.0.0",
        "postcss-minify-font-values@7.0.0",
        "postcss-minify-selectors@7.0.4",
        "postcss-normalize-charset@7.0.0",
        "postcss-normalize-display-values@7.0.0",
        "postcss-normalize-positions@7.0.0",
        "postcss-normalize-repeat-style@7.0.0",
        "postcss-normalize-string@7.0.0",
        "postcss-normalize-timing-functions@7.0.0",
        "postcss-normalize-url@7.0.0",
        "postcss-normalize-whitespace@7.0.0",
        "postcss-reduce-transforms@7.0.0",
        "postcss-unique-selectors@7.0.3",
        "postcss-convert-values@7.0.4",
        "postcss-minify-gradients@7.0.0",
        "colord@2.9.3",
        "postcss-minify-params@7.0.2",
        "postcss-normalize-unicode@7.0.2",
        "postcss-ordered-values@7.0.1",
        "postcss-colormin@7.0.2",
        "caniuse-api@3.0.0",
        "lodash.memoize@4.1.2",
        "lodash.uniq@4.5.0",
        "postcss-merge-longhand@7.0.4",
        "stylehacks@7.0.4",
        "postcss-merge-rules@7.0.4",
        "postcss-reduce-initial@7.0.2",
        "postcss-svgo@7.0.1",
        "svgo@3.3.2",
        "@trysound/sax@0.2.0",
        "commander@7.2.0",
        "css-what@6.1.0",
        "css-tree@2.3.1",
        "mdn-data@2.0.30",
        "csso@5.0.5",
        "css-tree@2.2.1",
        "mdn-data@2.0.28",
        "css-select@5.1.0",
        "boolbase@1.0.0",
        "domhandler@5.0.3",
        "domelementtype@2.3.0",
        "nth-check@2.1.1",
        "domutils@3.2.2",
        "dom-serializer@2.0.0",
        "entities@4.5.0",
      },
      "depth": Infinity,
      "dev": true,
      "filepath": "/Users/mac/develop/web/node-modules-checker/node_modules/.pnpm/debug@4.4.0_supports-color@9.4.0/node_modules/debug",
      "flatDependencies": Set {
        "@babel/core@7.26.7",
        "ms@2.1.3",
        "@babel/traverse@7.26.7",
      },
      "flatDependents": Set {
        "@babel/core@7.26.7",
        "untyped@1.5.2",
        "unbuild@3.3.1",
        "node-modules-tools@0.0.0",
        "package-manager-detector@0.2.9",
        "pathe@2.0.2",
        "pkg-types@1.3.1",
        "mlly@1.7.4",
        "mkdist@2.2.0",
        "tinyexec@0.3.2",
        "p-limit@6.2.0",
        "yocto-queue@1.1.1",
        "@pnpm/types@1000.1.1",
        "@pnpm/list@1000.0.7",
        "stream-json@1.9.1",
        "stream-chain@2.2.5",
        "confbox@0.1.8",
        "acorn@8.14.0",
        "ufo@1.5.4",
        "@types/stream-json@1.7.8",
        "@types/node@22.13.1",
        "@types/stream-chain@2.1.0",
        "undici-types@6.20.0",
        "@pnpm/crypto.polyfill@1000.0.0",
        "@pnpm/crypto.hash@1000.0.0",
        "@pnpm/dependency-path@1000.0.2",
        "@pnpm/reviewing.dependencies-hierarchy@1001.0.4",
        "archy@1.0.0",
        "@pnpm/ramda@0.28.1",
        "@pnpm/normalize-registries@1000.0.2",
        "p-limit@3.1.0",
        "yocto-queue@0.1.0",
        "chalk@4.1.2",
        "supports-color@7.2.0",
        "has-flag@4.0.0",
        "ansi-styles@4.3.0",
        "color-convert@2.0.1",
        "color-name@1.1.4",
        "cli-columns@4.0.0",
        "strip-ansi@6.0.1",
        "string-width@4.2.3",
        "ansi-regex@5.0.1",
        "emoji-regex@8.0.0",
        "is-fullwidth-code-point@3.0.0",
        "@pnpm/read-project-manifest@1000.0.5",
        "@gwhitney/detect-indent@7.0.1",
        "fast-deep-equal@3.1.3",
        "is-windows@1.0.2",
        "@pnpm/modules-yaml@1000.1.2",
        "json5@2.2.3",
        "@pnpm/write-project-manifest@1000.0.2",
        "strip-bom@4.0.0",
        "read-yaml-file@2.1.0",
        "@pnpm/error@1000.0.2",
        "@pnpm/read-package-json@1000.0.3",
        "@pnpm/constants@1001.1.0",
        "@pnpm/lockfile.fs@1001.1.2",
        "@pnpm/graceful-fs@1000.0.0",
        "graceful-fs@4.2.11",
        "load-json-file@6.2.0",
        "@pnpm/text.comments-parser@1000.0.0",
        "strip-comments-strings@1.2.0",
        "sort-keys@4.2.0",
        "is-plain-obj@2.1.0",
        "parse-json@5.2.0",
        "json-parse-even-better-errors@2.3.1",
        "lines-and-columns@1.2.4",
        "@babel/code-frame@7.26.2",
        "@babel/template@7.25.9",
        "@babel/helpers@7.26.7",
        "@babel/helper-validator-identifier@7.25.9",
        "@babel/types@7.26.7",
        "@babel/parser@7.26.7",
        "@babel/generator@7.26.5",
        "@babel/traverse@7.26.7",
        "@babel/helper-module-transforms@7.26.0",
        "js-tokens@4.0.0",
        "picocolors@1.1.1",
        "update-browserslist-db@1.1.2",
        "browserslist@4.24.4",
        "@babel/helper-compilation-targets@7.26.5",
        "error-ex@1.3.2",
        "is-arrayish@0.2.1",
        "js-yaml@4.1.0",
        "write-yaml-file@5.0.0",
        "argparse@2.0.1",
        "@zkochan/js-yaml@0.0.7",
        "write-file-atomic@5.0.1",
        "imurmurhash@0.1.4",
        "signal-exit@4.1.0",
        "type-fest@0.6.0",
        "normalize-package-data@5.0.0",
        "semver@7.7.1",
        "@pnpm/npm-package-arg@1.0.0",
        "hosted-git-info@6.1.3",
        "lru-cache@7.18.3",
        "is-core-module@2.16.1",
        "resolve@1.22.10",
        "@rollup/plugin-node-resolve@16.0.0",
        "hasown@2.0.2",
        "function-bind@1.1.2",
        "validate-npm-package-license@3.0.4",
        "spdx-expression-parse@3.0.1",
        "spdx-correct@3.2.0",
        "spdx-exceptions@2.5.0",
        "spdx-license-ids@3.0.21",
        "normalize-path@3.0.0",
        "realpath-missing@1.1.0",
        "resolve-link-target@2.0.0",
        "@pnpm/matcher@1000.0.0",
        "escape-string-regexp@4.0.0",
        "normalize-registry-url@2.0.0",
        "@pnpm/read-modules-dir@1000.0.0",
        "@pnpm/lockfile.detect-dep-types@1001.0.2",
        "@pnpm/lockfile.types@1001.0.2",
        "@pnpm/lockfile.utils@1001.0.2",
        "@pnpm/patching.types@1000.0.0",
        "@pnpm/pick-fetcher@1000.0.0",
        "get-npm-tarball-url@2.1.0",
        "@pnpm/resolver-base@1000.1.2",
        "hosted-git-info@4.1.0",
        "lru-cache@6.0.0",
        "yallist@4.0.0",
        "validate-npm-package-name@4.0.0",
        "builtins@5.1.0",
        "@pnpm/util.lex-comparator@3.0.0",
        "@zkochan/rimraf@3.0.2",
        "comver-to-semver@1.0.0",
        "@pnpm/lockfile.merger@1001.0.2",
        "@pnpm/git-utils@1000.0.0",
        "safe-execa@0.1.2",
        "path-name@1.0.0",
        "@zkochan/which@2.0.3",
        "isexe@2.0.0",
        "which@2.0.2",
        "cross-spawn@7.0.6",
        "execa@5.1.1",
        "get-stream@6.0.1",
        "human-signals@2.1.0",
        "is-stream@2.0.1",
        "merge-stream@2.0.0",
        "signal-exit@3.0.7",
        "strip-final-newline@2.0.0",
        "npm-run-path@4.0.1",
        "path-key@3.1.1",
        "onetime@5.1.2",
        "mimic-fn@2.1.0",
        "shebang-command@2.0.0",
        "shebang-regex@3.0.0",
        "@pnpm/logger@1000.0.0",
        "bole@5.0.17",
        "fast-safe-stringify@2.1.1",
        "individual@3.0.0",
        "ndjson@2.0.0",
        "json-stringify-safe@5.0.1",
        "minimist@1.2.8",
        "readable-stream@3.6.2",
        "split2@3.2.2",
        "inherits@2.0.4",
        "util-deprecate@1.0.2",
        "postcss-selector-parser@7.0.0",
        "postcss-nested@7.0.2",
        "string_decoder@1.3.0",
        "safe-buffer@5.2.1",
        "through2@4.0.2",
        "@rollup/plugin-alias@5.1.1",
        "consola@3.4.0",
        "citty@0.1.6",
        "defu@6.1.4",
        "esbuild@0.24.2",
        "hookable@5.5.3",
        "jiti@2.4.2",
        "pretty-bytes@6.1.1",
        "scule@1.3.0",
        "@rollup/pluginutils@5.1.4",
        "@rollup/plugin-commonjs@28.0.2",
        "@types/estree@1.0.6",
        "rollup@4.34.4",
        "rollup-plugin-dts@6.1.1",
        "estree-walker@2.0.2",
        "picomatch@4.0.2",
        "tinyglobby@0.2.10",
        "magic-string@0.30.17",
        "@rollup/plugin-replace@6.0.2",
        "@jridgewell/sourcemap-codec@1.5.0",
        "@jridgewell/trace-mapping@0.3.25",
        "@ampproject/remapping@2.3.0",
        "fdir@6.4.3",
        "commondir@1.0.1",
        "is-reference@1.2.1",
        "@rollup/plugin-json@6.1.0",
        "typescript@5.7.3",
        "@types/resolve@1.20.2",
        "deepmerge@4.3.1",
        "is-module@1.0.0",
        "path-parse@1.0.7",
        "supports-preserve-symlinks-flag@1.0.0",
        "@babel/standalone@7.26.7",
        "knitwork@1.2.0",
        "@babel/helper-string-parser@7.25.9",
        "convert-source-map@2.0.0",
        "gensync@1.0.0-beta.2",
        "semver@6.3.1",
        "@jridgewell/gen-mapping@0.3.8",
        "postcss-calc@10.1.1",
        "cssnano-preset-default@7.0.6",
        "cssnano@7.0.6",
        "postcss-selector-parser@6.1.2",
        "postcss-discard-comments@7.0.3",
        "postcss-minify-selectors@7.0.4",
        "postcss-unique-selectors@7.0.3",
        "stylehacks@7.0.4",
        "postcss-merge-longhand@7.0.4",
        "postcss-merge-rules@7.0.4",
        "autoprefixer@10.4.20",
        "postcss-convert-values@7.0.4",
        "postcss-minify-params@7.0.2",
        "postcss-normalize-unicode@7.0.2",
        "postcss-colormin@7.0.2",
        "caniuse-api@3.0.0",
        "postcss-reduce-initial@7.0.2",
        "postcss@8.5.1",
        "css-declaration-sorter@7.2.0",
        "cssnano-utils@5.0.0",
        "postcss-minify-gradients@7.0.0",
        "postcss-ordered-values@7.0.1",
        "postcss-discard-duplicates@7.0.1",
        "postcss-discard-empty@7.0.0",
        "postcss-discard-overridden@7.0.0",
        "postcss-minify-font-values@7.0.0",
        "postcss-normalize-charset@7.0.0",
        "postcss-normalize-display-values@7.0.0",
        "postcss-normalize-positions@7.0.0",
        "postcss-normalize-repeat-style@7.0.0",
        "postcss-normalize-string@7.0.0",
        "postcss-normalize-timing-functions@7.0.0",
        "postcss-normalize-url@7.0.0",
        "postcss-normalize-whitespace@7.0.0",
        "postcss-reduce-transforms@7.0.0",
        "postcss-svgo@7.0.1",
        "svgo@3.3.2",
        "@babel/helper-module-imports@7.25.9",
      },
      "name": "debug",
      "resolved": {
        "author": "Josh Junon (https://github.com/qix-)",
        "engines": {
          "node": ">=6.0",
        },
        "homepage": undefined,
        "installSize": {
          "bytes": NaN,
          "categories": {
            "doc": {
              "bytes": 22115,
              "count": 1,
            },
            "json": {
              "bytes": 1524,
              "count": 1,
            },
            "other": {
              "bytes": 1139,
              "count": 1,
            },
            "undefined": {
              "bytes": NaN,
              "count": 4,
            },
          },
        },
        "license": "MIT",
        "module": "cjs",
        "repository": "github.com/debug-js/debug",
      },
      "spec": "debug@4.4.0",
      "version": "4.4.0",
    }
  `)
})
